version: '3'
services:
  php:
    image: webdevops/php-nginx-dev:8.0
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=-1
      - PHP_MAX_EXECUTION_TIME=-1
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_MAX_NESTING_LEVEL=1000
      - PHP_DISMOD=ioncube
      - COMPOSER_VERSION=2
      - COMPOSER_MEMORY_LIMIT=-1
      - APP_ENV=dev
      - APP_DEBUG=1
    ports:
      - "8080:80"
    volumes:
      - ./:/app:rw
      - /app/var/cache
      - ./config/permissions.sh:/opt/docker/provision/entrypoint.d/permissions.sh